# Site settings
title: Manoj Homeo | Dr. Abhishek Kumar Lalganj
description: "Bimaari aapki Takleef humari"
baseurl: "/manojHomeo" # the subpath of your site, e.g. /blog
url: "https://manna018.github.io" # the name of your domain
logo_url: svg/mainLogo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Dr. Abhishek Kumar
    hero_description: BHMS 

# Contact form
api_token: xvownnna # Enter API token here  Formspree

# Contact info
contact:
    phone: 82 5253 7677
    emergency: 82 5253 7677
    email: doctorkumar01@gmail.com
    address: House No. 34, Ward, No. 6, Library Rd, Manpur Patwatoli, Lalganj, Bihar 844121

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2020 Manoj Homeo - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
